name: newsextra
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fast_i18n: ^5.11.0
  dio: ^4.0.4
  provider: ^6.0.2
  transparent_image: ^2.0.0
  pull_to_refresh: ^2.0.0
  share_plus: ^4.1.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.0.13
  flutter_sim_country_code: ^0.1.2
  better_player: ^0.0.83
  youtube_player_flutter: ^8.1.0
  flutter_web_browser: "^0.17.1"
  google_sign_in: ^5.2.4
  email_validator: "^2.0.1"
  font_awesome_flutter: ^9.2.0
  flutter_login_facebook: ^1.4.1
  sign_in_apple: ^2.0.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  flutter_local_notifications: ^9.4.0
  audiofileplayer: ^2.1.0
  intl: ^0.18.1
  sqflite: ^2.0.2
  path: ^1.8.0
  platform_device_id: ^1.0.1
  google_mobile_ads: ^5.1.0
  #open_app_settings: ^2.0.1
  #permission_handler: ^10.2.0
  badges: ^2.0.2
  flash: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # An image asset can refer to on
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
